AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nrl-news-lambda
  
Globals:
  Function:
    Timeout: 5

Resources:
  NRLNewsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: get-news/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: nrl-bucket-latest-news
      Events:
        GetNrlNews:
          Type: Api 
          Properties:
            Path: /news
            Method: get

Outputs:
  NewsApi:
    Description: "API Gateway endpoint URL for NRL News"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/news/"
  NRLNewsFunction:
    Description: "NRL News Lambda Function ARN"
    Value: !GetAtt NRLNewsFunction.Arn
  NRLNewsFunctionIamRole:
    Description: "Implicit IAM Role created for NRL News"
    Value: !GetAtt NRLNewsFunctionRole.Arn
